# This is a basic workflow to help validate your Terraform configuration

name: Pull Request after validate

# Controls when the workflow will run
on:
  workflow_run:
    workflows: ["Validate Infrastructure"]
    types:
      - completed
    branches-ignore:
      - 'main'
  workflow_dispatch:


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    # This workflow contains a single job called "Security Check"
    terraform:
      name: 'Security Check'
      # The type of runner that the job will run on
      runs-on: ubuntu-latest
      
      env:
        ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        WORKING_DIR: ./Modul09
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
      # Steps represent a sequence of tasks that will be executed as part of the job
      steps:
        - name: 'Create Pull Request'
          uses: peter-evans/create-pull-request@v4
          with:
            token: ${{ secrets.GITHUB_TOKEN }}
            commit-message: 'chore: merge ${GITHUB_REF} into main'
            title: 'Merge ${GITHUB_REF}: [Your feature description]'
            body: |
                This PR was auto-generated by a GitHub Action to merge changes from ${GITHUB_REF} into main.
            base: 'main'  # Base branch to merge into
            branch: 'auto-pr/${{ github.event.workflow_run.head_branch }}'  # Name of the branch for the PR